-- -- GoRide Trip & Matching — driver_offers
-- --
-- -- Tracks which drivers a trip request was offered to (one row per trip+driver)
-- -- and what each driver did with it. Status: Pending, Accepted, Declined,
-- -- Expired, Failed.
-- --
-- -- Run this against trip_db using the Azure MySQL server's ADMIN login — the
-- -- service's own user (trip_svc) is scoped to trip_db and normally can't create
-- -- tables. The app also tries to create the table on startup
-- -- (DriverOfferRepository.EnsureSchemaAsync), but that is CREATE IF NOT EXISTS:
-- -- it does nothing if a table with this name already exists, even one with a
-- -- different layout. So an older driver_offers must be moved aside first (step 1).
-- --
-- -- trip_id deliberately has no foreign key to `trips` and is VARCHAR(64): the
-- -- frontend's trip ids ("trp_" + a UUID) are 40 characters, longer than char(36).

-- USE trip_db;

-- -- ---------------------------------------------------------------------------
-- -- 1. If driver_offers ALREADY EXISTS with the older layout (columns id, trip_id,
-- --    driver_id, round, offered_at, responded_at, response), move it aside. This
-- --    keeps its data; nothing is dropped. Skip this step on a brand-new database.
-- --    Drop the old copy yourself later:  DROP TABLE driver_offers_old;
-- -- ---------------------------------------------------------------------------
-- -- RENAME TABLE driver_offers TO driver_offers_old;

-- -- ---------------------------------------------------------------------------
-- -- 2. Create the table the service uses.
-- -- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS driver_offers (
--     trip_id          VARCHAR(64)   NOT NULL,
--     driver_id        VARCHAR(64)   NOT NULL,
--     rider_id         VARCHAR(64)   NOT NULL,
--     status           VARCHAR(16)   NOT NULL DEFAULT 'Pending',
--     distance_km      DOUBLE        NOT NULL,
--     pickup_location  VARCHAR(255)  NULL,
--     pickup_lat       DOUBLE        NULL,
--     pickup_lng       DOUBLE        NULL,
--     dropoff_location VARCHAR(255)  NULL,
--     dropoff_lat      DOUBLE        NULL,
--     dropoff_lng      DOUBLE        NULL,
--     fare             DECIMAL(10,2) NULL,
--     created_at       DATETIME(3)   NOT NULL,
--     decided_at       DATETIME(3)   NULL,
--     arrived_at       DATETIME(3)   NULL,
--     started_at       DATETIME(3)   NULL,
--     completed_at     DATETIME(3)   NULL,
--     PRIMARY KEY (trip_id, driver_id),
--     INDEX idx_driver_offers_driver_status (driver_id, status)
-- );

-- -- ---------------------------------------------------------------------------
-- -- 2b. SCRUM-82: if you already had driver_offers from before this column set
-- --    (pickup/dropoff coordinates + the arrived/started/completed timestamps),
-- --    the CREATE above was a no-op, so add them by hand instead. Run this block
-- --    ONCE -- unlike the CREATE above, plain ADD COLUMN errors ("Duplicate
-- --    column name") if a column already exists, because this Azure MySQL
-- --    version predates 8.0.29's ADD COLUMN IF NOT EXISTS support. If it fails
-- --    partway through, check `DESCRIBE driver_offers` and delete the lines for
-- --    whichever columns already landed, then re-run the rest.
-- -- ---------------------------------------------------------------------------
-- ALTER TABLE driver_offers
--     ADD COLUMN pickup_lat   DOUBLE      NULL AFTER pickup_location,
--     ADD COLUMN pickup_lng   DOUBLE      NULL AFTER pickup_lat,
--     ADD COLUMN dropoff_lat  DOUBLE      NULL AFTER dropoff_location,
--     ADD COLUMN dropoff_lng  DOUBLE      NULL AFTER dropoff_lat,
--     ADD COLUMN arrived_at   DATETIME(3) NULL AFTER decided_at,
--     ADD COLUMN started_at   DATETIME(3) NULL AFTER arrived_at,
--     ADD COLUMN completed_at DATETIME(3) NULL AFTER started_at;

-- -- ---------------------------------------------------------------------------
-- -- 3. Only if trip_svc has rights per table rather than on all of trip_db:
-- -- ---------------------------------------------------------------------------
-- -- GRANT SELECT, INSERT, UPDATE ON trip_db.driver_offers TO 'trip_svc'@'%';

-- ---------------------------------------------------------------------------
-- SCRUM-62: only the first valid driver acceptance succeeds. trip_id is this
-- table's PRIMARY KEY, so InnoDB itself guarantees at most one driver can ever
-- successfully INSERT a claim row for a given trip, even if several accept at
-- the exact same instant -- see DriverOfferRepository.TryAcceptAsync. Run
-- this against trip_db with the admin login, same as driver_offers above.
-- ---------------------------------------------------------------------------
-- USE trip_db;

-- CREATE TABLE IF NOT EXISTS trip_claims (
--     trip_id    VARCHAR(64) NOT NULL,
--     driver_id  VARCHAR(64) NOT NULL,
--     claimed_at DATETIME(3) NOT NULL,
--     PRIMARY KEY (trip_id)
-- );

-- Only if trip_svc has rights per table rather than on all of trip_db:
-- GRANT SELECT, INSERT, DELETE ON trip_db.trip_claims TO 'trip_svc'@'%';
