services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: goride-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "goride-local-cluster-1"

  service-api:
    build: .
    container_name: goride-trip-api
    ports:
      - "8080:8080"
    environment:
      Db__Host: ${DB_HOST}
      Db__Port: ${DB_PORT}
      Db__Database: ${DB_DATABASE}
      Db__User: ${DB_USER}
      Db__Password: ${DB_PASSWORD}
      Db__SslMode: Required
      Kafka__BootstrapServers: "kafka:9092"
      Cors__AllowedOrigins__0: ${FRONTEND_URL_LOCAL}
      Cors__AllowedOrigins__1: ${FRONTEND_URL_PROD}
    env_file:
      - .env
    depends_on:
      - kafka